#!/bin/bash

docker build \
  --build-arg BUILD_VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg BUILD_VERSION=`git describe` \
  -t $IMAGE_NAME .
